### ISSUE TITLE
Bulk download and authentication not working

### ISSUE THREAD

**Issue by thecoffeebin** [arabcoders/ytptube#310]
I've just updated my docker to the latest version v0.1.3

1. Noticed that the basic authentication now prompts every time I reload my site (YTP) which did not happen before (for eg. in v0.1.1), is this something that can be fixed? I'm expecting the authentication to stick across reload/refresh of browser.
2. Bulk download (multiple select on checkboxes) does not work, as it only downloads one file and then finished. To be honest I have not tested this before ever since I installed YTP (since v0.1.0?) so I couldn't judge if this is a new bug or is a default behavior. However bulk remove using the same way, works. So I'm expecting bulk download will allow me to download a single ZIP with all my selected files.

Thanks in advanced for looking into these! Great app nonetheless!

**Comment by thecoffeebin** [comment]
> > Noticed that the basic authentication now prompts every time I reload my site (YTP) which did not happen before (for eg. in v0.1.1), is this something that can be fixed? I'm expecting the authentication to stick across reload/refresh of browser.
> 
> No, this is not intended please try to hard refresh and confirm you have the authentication cookie after you sign in.
> 
> > Bulk download (multiple select on checkboxes) does not work, as it only downloads one file and then finished. To be honest I have not tested this before ever since I installed YTP (since v0.1.0?) so I couldn't judge if this is a new bug or is a default behavior. However bulk remove using the same way, works. So I'm expecting bulk download will allow me to download a single ZIP with all my selected files.
> 
> Bulk download is actually browser dependent, you most likely have gotten a notification to allow multiple downloads and you didn't notice or declined thats probably why you are only getting one file. Check the site permission to allow multiple downloads.

Can confirm Bulk download is working as intended, indeed it's due to site permission to enable multiple downloads.

As for authentication it's still not working for me, I checked that there's no cookie recorded after login. I've tested this in both browsers Chrome and Mozilla with the same behavior (keep prompting for user/password). Probably I need to rebuild the container to see if it works with a fresh start.

**Comment by arabcoders** [comment]
> As for authentication it's still not working for me, I checked that there's no cookie recorded after login

Ok thanks for confirming i will investigate the login path.

**Comment by arabcoders** [comment]
@thecoffeebin fixed in v0.1.4

**Comment by arabcoders** [comment]
> @arabcoders Thanks for the quick turnaround. However I kept receiving the authentication popup even though I have entered correct username/password, and I also noticed a cookie ('auth') is created. Once I clicked cancelled I can see my history but the page is obviously disoriented (probably CSS is not fully loaded, not sure).
> 
> So yeah the authentication is still a problem in v0.1.4 (popping up continuously despite correct credential has entered).

Weird tested it on free different browsers all working as expected. 

please try in private window and see if this fixes the problem for you

**Comment by thecoffeebin** [comment]
Sorry! I found out the root cause of my issue. I downgraded to v0.1.2 and v0.1.1 and the issue persists, so in the end I actually have to turn off Cache Assets setting in my reverse proxy (Nginx Proxy Manager) and voila, problem solved!

![Image](https://github.com/user-attachments/assets/e103a32c-e3bf-4fa5-a5d0-d8c5e9991910)

Thank you once again for your help and what a wonderful app this is!

**Comment by arabcoders** [comment]
> Sorry! I found out the root cause of my issue. I downgraded to v0.1.2 and v0.1.1 and the issue persists, so in the end I actually have to turn off Cache Assets setting in my reverse proxy (Nginx Proxy Manager) and voila, problem solved!
> 
> ![Image](https://github.com/user-attachments/assets/e103a32c-e3bf-4fa5-a5d0-d8c5e9991910)
> 
> Thank you once again for your help and what a wonderful app this is!

Glad everything is working for you.

**Comment by thecoffeebin** [comment]
Hi @arabcoders sorry have to reopen this issue. Bulk download works but only for 10 simultaneous downloads although I've checked/selected 100 files to download. I can't find any limitation from my browser so I think it could be hard-coded or hidden somewhere, or is it a thing on YTPtube?

**Comment by thecoffeebin** [comment]
@arabcoders Thanks for your response. I think there's a misunderstanding on bulk download in your last reply. I didn't mean to download more than two streams from youtube, in fact I'm trying to bulk download from local videos of YTPtube (already pulled from Youtube). I believe the `config.max_workers` you mean above is more of processing downloads from Youtube.

So the scenario is that I downloaded a playlist from Youtube consist of 100 songs (in m4a) and they've been successfully downloaded to YTPtube. Now I'm trying to fetch/download them to my computer, here's what has become tricky, no matter how many checkboxes I checked it will only prompt me to download maximum of 10 videos (one by one....) and then it stopped processing. I don't even know how to continue to download the next batch because there's no indicator of which videos had been downloaded.

In ideal situation, I would prefer YTPtube to zip all checked items in YTPtube, and send a large zip file for me to download.

**Comment by arabcoders** [comment]
I refactored the global download button to download files as zip archive with any sidecar files.
